name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (ex: dev1, rc1)'
        required: false
        default: 'dev'

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Build with uv
        run: uv build

      - name: Send to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
